version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - stellcoilbench update-db
    build:
      html:
        - sphinx-build -b html docs $READTHEDOCS_OUTPUT/html/

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - DOCS
    - requirements: docs/requirements.txt
