version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - stellcoilbench update-db

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - DOCS
    - requirements: docs/requirements.txt
